services:
  memoriaworks-docker-subversion:
    build:
      no_cache: true
      context: .
      dockerfile: ./Dockerfile
      args:
        SVN_BASE: /data/svn
        SVN_GROUP: svnusers
        SVN_SHELL: svnonly
        SSHD_OPTS: ""
    restart: unless-stopped
    container_name: 'subversion'
    working_dir: '/data/svn'
    environment:
      # SVN_LOCAL_ADMIN_USER and SVN_LOCAL_ADMIN_PASS
      # can be enabled if there is no pre-existing .htpasswd
      # SVN_LOCAL_ADMIN_USER: admin
      # SVN_LOCAL_ADMIN_PASS: myp4ass
      SUBVERSION_REPOS: azura/engine;azura/game;azura/raw
      DESCRIPTION_azura: Azura
      SSHD_OPTS: "-f /data/sshd_config"
      MASTER_AUTHZ: /data/svn/.svn.access
    ports:
      - "95:80"
      - "3690:3690"
      # set SSH to default 22 in conf and expose arbitrarily here
      - "41837:22"
    volumes:
      # make sure ../../.volumes/svn/docker-subversion/repos_iaean
      # is owned by 100:101 (apache:apache)
      - ../../.volumes/svn/docker-subversion/repos_iaean:/data/svn:rw
      - ../../.volumes/svn/docker-subversion/secrets/__SECRET__.htpasswd:/data/svn/.htpasswd:rw
      - ../../.volumes/svn/docker-subversion/secrets/__SECRET__.svn.access:/data/svn/.svn.access:rw
      - ../../.volumes/svn/docker-subversion/etc/subversion/svnserve.conf:/etc/subversion/svnserve.conf:ro
      - ./ssh/sshd_config:/data/sshd_config:ro
      - ./svn/hooks:/data/hooks:ro
      # /home
      #
      # sudo rsync -rhav --progress /home/ $(git rev-parse --show-toplevel)/docker-compose/sites/memoriaworks/.volumes/svn/docker-subversion/home/ --dry-run
      #
      # or
      #
      # mount /home directory with its contents for testing
      # Todo: move /home of host to .volumes/svn as they are no longer relevant system wide
      - ../../.volumes/svn/docker-subversion/home:/home:rw
      # /etc/{shadow,shadow-}
      #
      # sudo touch ./static/etc/{shadow,shadow-}
      # sudo chown 0:42 ./static/etc/{shadow,shadow-}
      # sudo chmod 0640 ./static/etc/{shadow,shadow-}
      #
      # or
      #
      # sudo cp -rp /etc/{shadow,shadow-} $(git rev-parse --show-toplevel)/docker-compose/sites/memoriaworks/svn/docker-subversion/static/etc/
      # or
      # ln -s /etc/{shadow,shadow-} $(git rev-parse --show-toplevel)/docker-compose/sites/memoriaworks/svn/docker-subversion/static/etc/{shadow,shadow-}
      # or
      # sudo rsync -hv --progress /etc/{shadow,shadow-} $(git rev-parse --show-toplevel)/docker-compose/sites/memoriaworks/svn/docker-subversion/static/etc/ --dry-run
      - ./static/etc/shadow:/etc/shadow:rw
      - ./static/etc/shadow-:/etc/shadow-:rw
      # /etc/{group,group-}
      # sudo touch ./static/etc/{group,group-}
      # sudo chown 0:0 ./static/etc/{group,group-}
      # sudo chmod 0644 ./static/etc/{group,group-}
      #
      # or
      #
      # sudo cp -rp /etc/{group,group-} $(git rev-parse --show-toplevel)/docker-compose/sites/memoriaworks/svn/docker-subversion/static/etc/
      # or
      # ln -s /etc/{group,group-} $(git rev-parse --show-toplevel)/docker-compose/sites/memoriaworks/svn/docker-subversion/static/etc/{group,group-}
      # or
      # sudo rsync -hv --progress /etc/{group,group-} $(git rev-parse --show-toplevel)/docker-compose/sites/memoriaworks/svn/docker-subversion/static/etc/ --dry-run
      - ./static/etc/group:/etc/group:rw
      - ./static/etc/group-:/etc/group-:rw
      # /etc/sudoers ???
      # /etc/sudoers.d ???
      # /etc/ufw ???
