Alias /websvn /var/www/html/
<Directory /var/www/html/>
  AllowOverride None
  Options Indexes

  AuthType Basic
  AuthName "Local Account"
  AuthBasicProvider file
  AuthUserFile /data/svn/.htpasswd
  Require valid-user
</Directory>
